<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart">
    <div class="page-title title-buttons">
        <!--<h1><?php echo $this->__('Shopping Cart') ?></h1>-->
        <?php if(!$this->hasError()): ?>
        <ul class="checkout-types">
        <?php foreach ($this->getMethods('top_methods') as $method): ?>
            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
            <li><?php echo $methodHtml; ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?>
    </div>
	<div style=""><ul class="messages"><li class="success-msg"><ul><li><span>Product has been successfully removed from your cart.&nbsp;<?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getContinueShoppingUrl()) ?></span></li></ul></li></ul></div>
    if (!empty($childHtmlCoupon) || !empty($childHtmlShipping)) :?>
	<!--Changes by LIKI Ext Start-->
	<!--Reason of Change: We did changes because After removing the product then there was displaying a pop-up.We removed the lower details from the pop up because it was not required.-->
    <!--<div id="invader" class="triangle-down" ></div>-->
	<!--Changes by LIKI Ext End-->
	<!--LIKI Code END-->
    <script type="text/javascript">
    //<![CDATA[
        var ajaxproCartCollateralsToggle = function() {
            var element = $('invader');
            if (!element) {
                return;
            }
            var toogleElement = element.next('.cart-collaterals');
            if (!toogleElement) {
                return;
            }
            Effect.toggle(toogleElement, 'appear', {duration: .2});

            var addClass = 'triangle-up', removeClass = 'triangle-down';
            if (toogleElement.visible()) {
                addClass = 'triangle-down'; removeClass = 'triangle-up';
            }
            element.addClassName(addClass);
            element.removeClassName(removeClass);
            return false;
        }
        $('invader').observe('click', ajaxproCartCollateralsToggle);

        AjaxPro.observe([
            'onComplete:checkout:cart:couponPost',
            'onFailure:checkout:cart:couponPost',
            'onComplete:checkout:cart:estimatePost',
            'onFailure:checkout:cart:estimatePost',
            'onComplete:checkout:cart:estimateUpdatePost',
            'onFailure:checkout:cart:estimateUpdatePost'
        ], ajaxproCartCollateralsToggle);
    //]]>
    </script>

    <div class="cart-collaterals" style="display: none">
        <div class="col2-set">
            <div class="col-1">
                <?php if (!$this->getIsVirtual()): echo $childHtmlShipping; endif; ?>
            </div>
            <div class="col-2">
                <?php echo $childHtmlCoupon ?>
            </div>
        </div>
    </div>
    <?php endif;?>
</div>
