<style>
.category-title{display: none;}
</style>
<?php
	$categories = Mage::getModel('catalog/category')
	->getCollection()
	->addAttributeToSelect('*')
	->addIsActiveFilter();
	
	$ids = array(3559,3561,3562,4220,3660,3662); 
?>
<div class="home-catlist" style="float:left;margin-bottom:50px;width:auto;"> 
	<?php
	foreach ($categories as $category)
	{
	  if( in_array($category->getId(),$ids) )
		{
	 ?>
	<div class="subcat_homelist">
		<a href="<?php echo $category->getUrl() ?>" title="<?php echo $category->getName() ?>">
			<img src="<?php echo Mage::getBaseUrl('media')?>catalog/category/<?php echo $category->getThumbnail()?>" alt="<?php echo 
			$category->getName() ?>" width="180" height="180"/>
			 <span class="spantitle"> Shop <?php echo $category->getName() ?></span>
		</a>
	 </div>
	 <?php
		}
	} ?> 
</div>
