<?php
//LIKi Changes 
//Reason:Style changes
$_helper           =  Mage::helper('catalogsearch');
$_value            = $_helper->getEscapedQueryText();
$_currentCategory  = Mage::getSingleton('core/app')->getRequest()->getParam('cat');
$_currentAttribute = Mage::getSingleton('core/app')->getRequest()->getParam('attr');
$_filterType       = $this->getFilterType();
$_url              = $this->getAjaxUrl();
?>
<!-- Changes Start for onpage SEO to remove html errors -->
<style type="text/css">
.nav .UI-NAV-INPUT{padding:0 !important}
.searchautocomplete .nav {width:270px !important;}
.UI-SEARCHAUTOCOMPLETE .nav-submit-button .search:hover {background-color: #E6791E !important}
</style>
<!-- Changes for onpage SEO End -->
<form style="position:inherit; width:315px; float:right; padding:15px 0 4px 20px; height:37px" class="searchautocomplete UI-SEARCHAUTOCOMPLETE" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get"
    data-tip="<?php echo $this->__(Mage::getStoreConfig('searchautocomplete/general/tip')) ?>"
    data-url="<?php echo $_url ?>"
    data-minchars="<?php echo Mage::getStoreConfig('searchautocomplete/general/min_chars') ?>"
    data-delay="<?php echo Mage::getStoreConfig('searchautocomplete/general/delay') ?>">
    <div class="nav" style="height:36px; float:left; background:#f6f6f6;">
        <div class="nav-input UI-NAV-INPUT" >
            <input onkeyup="trim_search()" id="search" style="width: 97%;opacity: 1;color: #7f7f7f;" class="input-text UI-SEARCH" type="text" autocomplete="off" name="<?php echo $_helper->getQueryParamName() ?>" value="<?php echo $_helper->getEscapedQueryText() ?>" maxlength="<?php echo $_helper->getMaxQueryLength() ?>" />
        </div>
        <div class="searchautocomplete-loader UI-LOADER" style="display:none;"></div>
    </div>
    <div class="nav-submit-button">
	<button class="search" style="background:url(/skin/frontend/argento/default/images/search_btn_trans.png);background-color: #ff851e; border-radius: 0px;height: 38px;background-color: #ff851e;border-radius: 0px;height: 38px;width: 38px;height: 38px;padding: 0px 9px;margin: 0px;cursor: pointer;font-weight: bold;color: white;line-height: 12px;
font-size: 13px;
border: 0px;" type="submit"></button>
       
    </div>
	<!--LIKI Code Start
		Reason : look & feel change-->
    <div style="display: none; position:relative;top: 42px;left: 0px;" class="searchautocomplete-placeholder UI-PLACEHOLDER"></div>
	<!--LIKI Code End-->
</form>

<script type="text/javascript"> 
function trim_search()
	{
		var search_text = document.getElementById('search').value;
		search_text = search_text.replace(/^\s+|\s+$/g,'');
		if(search_text == ''){document.getElementById('search').value = '';}
	}
</script>	

