<div class="page-title">
   <h1><?php echo Mage::helper('sales')->__('Returns') ?></h1>
</div>
<div class="block-content">
   <form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
<!-- changes by likiext -->	<div class="oar_widget_orders_and_returns_form">
	<h2 class="order_return">Orders and Returns</h2> <!-- changes by likiext end-->
       <ul class="form-alt">
<!-- changes by likiext -->   <li style="clear:both;float:left;margin:10px 0 10px 0;"> <!-- changes by likiext end-->
               <div class="input-box" style="float:left;width:150px;">
                   <label for="oar_order_id" class="required"><?php echo Mage::helper('sales')->__('Order ID') ?> <em><span style="color:#f00;">*</span></em></label>
               </div>
               <div class="input-box" style="float:left;width:305px;">
                   <input type="text" class="input-text required-entry" id="oar_order_id" name="oar_order_id" style="width:300px;" onkeydown="remove_error('oar_order_id', 'advice-required-entry-oar_order_id')" />
               </div>
           </li>
<!-- changes by likiext -->        <li style="clear:both;float:left;margin:5px 0 15px 0;">
        <div class="input-box" style="font-size:12px;"> <!-- changes by likiext end-->
<!-- changes by likiext -->                  <?php echo Mage::helper('sales')->__('Enter the billing last name and Email/ZIP as in the order billing address') ?>. <!-- changes by likiext end-->
                </div>
           </li>
<!-- changes by likiext -->   <li style="clear:both;float:left;margin-bottom:15px;"> <!-- changes by likiext end-->
               <div class="input-box" style="float:left;width:150px;">
<!-- changes by likiext -->                   <label for="oar_billing_lastname" class="required"><?php echo Mage::helper('sales')->__('Billing Last Name') ?> <em><span style="color:#f00;">*</span></em></label> <!-- changes by likiext end-->
               </div>
               <div class="input-box" style="float:left;width:305px;">
<!-- changes by likiext -->                   <input type="text" class="input-text required-entry" id="oar_billing_lastname" name="oar_billing_lastname"  style="width:300px;" onkeydown="remove_error('oar_billing_lastname', 'advice-required-entry-oar_billing_lastname')" /> <!-- changes by likiext end-->
               </div>
           </li>
<!-- changes by likiext -->           <li style="clear:both;float:left;margin-bottom:15px;"> <!-- changes by likiext end-->
               <div class="input-box" style="float:left;width:150px;">
                   <label class="required"><?php echo Mage::helper('sales')->__('Find Order By:') ?></label>
               </div>
<!-- changes by likiext -->                <div class="input-box" style="float:left;width:300px;"> <!-- changes by likiext end-->
                   <select name="oar_type" id="quick_search_type_id" class="select guest-select" title="" onchange="showIdentifyBlock(this.value);">
                       <option value="email">Email Address</option>
                       <option value="zip">ZIP Code</option>
                   </select>
               </div>
           </li>
<!-- changes by likiext -->           <li id="oar-email" style="clear:both;float:left;margin-bottom:15px;"> <!-- changes by likiext end-->
               <div class="input-box" style="float:left;width:150px;">
<!-- changes by likiext -->                   <label for="oar_email" class="required"><?php echo Mage::helper('sales')->__('Email Address') ?> <em><span style="color:#f00;">*</span></em></label> <!-- changes by likiext end-->
               </div>
               <div class="input-box" style="float:left;width:305px;">
<!-- changes by likiext -->                   <input type="text" class="input-text validate-email required-entry" id="oar_email" name="oar_email"  style="width:300px;" onkeydown="remove_error('oar_email', 'advice-required-entry-oar_email')" /> <!-- changes by likiext end-->
               </div>
           </li>
<!-- changes by likiext -->           <li id="oar-zip" style="display:none;clear:both;float:left;margin-bottom:15px;"> <!-- changes by likiext end-->
               <div class="input-box" style="float:left;width:150px;">
<!-- changes by likiext -->                   <label for="oar_zip" class="required"><?php echo Mage::helper('sales')->__('Billing ZIP Code') ?> <em><span style="color:#f00;">*</span></em></label> <!-- changes by likiext end-->
               </div>
               <div class="input-box" style="float:left;width:305px;">
                   <input type="text" class="input-text required-entry" id="oar_zip" name="oar_zip" style="width:300px;"/>
               </div>
           </li>
<!-- changes by likiext -->       </ul>
       </div> <!-- changes by likiext end-->
       
<!-- changes by likiext -->       <div class="input-box" style="float:left;text-align:right;width:99%;margin-bottom:10px;">
            <p class="required" style="margin-bottom:10px;">* Required Fields</p> <!-- changes by likiext end-->
           <button type="submit" title="Continue" class="button"><span><span><?php echo Mage::helper('sales')->__('Continue') ?></span></span></button>
       </div>
           
   </form>
</div>
<script type="text/javascript">
//<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
       $('oar-zip').hide();
       $('oar-email').show();
    }

   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
//]]>

</script>
