<?php
$saleHelper =  Mage::helper('sales');
?>
<div class="page-title">
   <h1><?php echo $saleHelper->__('Returns') ?></h1>
</div>
<div class="block-content">
   <form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="search-form" name="guest_post">
	<!-- changes by likiext -->
		<div class="oar_widget_orders_and_returns_form">
		<h2 class="order_return">Orders and Returns</h2>
       <ul class="form-alt">
		<li style="clear:both;float:left;margin:10px 0 10px 0;">
               <div class="input-box" style="float:left;width:150px;">
                   <label for="oar_order_id" class="required"><?php echo $saleHelper->__('Order ID') ?> <em><span style="color:#f00;">*</span></em></label>
               </div>
               <div class="input-box" style="float:left;width:305px;">
				   	<input type="text" class="input-text required-entry" id="oar_order_id" name="oar_order_id" style="width:300px;" />
               </div>
         </li>
		<li style="clear:both;float:left;margin:5px 0 15px 0;">
        <div class="input-box" style="font-size:12px;">
				<?php echo $saleHelper->__('Enter the billing last name and Email/ZIP as in the order billing address') ?>.
                </div>
           </li>
		   <li style="clear:both;float:left;margin-bottom:15px;">
               <div class="input-box" style="float:left;width:150px;">
					<label for="oar_billing_lastname" class="required"><?php echo $saleHelper->__('Billing Last Name') ?> <em><span style="color:#f00;">*</span></em></label>
               </div>
               <div class="input-box" style="float:left;width:305px;">
					<input type="text" class="input-text required-entry" id="oar_billing_lastname" name="oar_billing_lastname"  style="width:300px;" />
               </div>
           </li>
		   <li style="clear:both;float:left;margin-bottom:15px;">
               <div class="input-box" style="float:left;width:150px;">
                   <label class="required"><?php echo $saleHelper->__('Find Order By:') ?></label>
               </div>
			   <div class="input-box" style="float:left;width:300px;">
                   <select name="oar_type" id="quick_search_type_id" class="select guest-select" title="" onchange="showIdentifyBlock(this.value);">
                       <option value="email">Email Address</option>
                       <option value="zip">ZIP Code</option>
                   </select>
               </div>
           </li>
		   <li id="oar-email" style="clear:both;float:left;margin-bottom:15px;">
               <div class="input-box" style="float:left;width:150px;">
					<label for="oar_email" class="required"><?php echo $saleHelper->__('Email Address') ?> <em><span style="color:#f00;">*</span></em></label>
               </div>
               <div class="input-box" style="float:left;width:305px;">
					<input type="text" class="input-text validate-email required-entry" id="oar_email" name="oar_email"  style="width:300px;" />
               </div>
           </li>
		   <li id="oar-zip" style="display:none;clear:both;float:left;margin-bottom:15px;">
               <div class="input-box" style="float:left;width:150px;">
					<label for="oar_zip" class="required"><?php echo $saleHelper->__('Billing ZIP Code') ?> <em><span style="color:#f00;">*</span></em></label>
               </div>
               <div class="input-box" style="float:left;width:305px;">
                   <input type="text" class="input-text required-entry" id="oar_zip" name="oar_zip" style="width:300px;"/>
               </div>
           </li>
		</ul>
       </div>
	   <div class="input-box" style="float:left;text-align:right;width:99%;margin-bottom:10px;">
            <p class="required" style="margin-bottom:10px;">* Required Fields</p> 
      <!-- changes by likiext end-->
           <button type="submit" title="Continue" class="button"> <span><span><?php echo $saleHelper->__('Continue') ?></span></span></button>
       </div>
           
   </form>
</div>
<script type="text/javascript">
//<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
       $('oar-zip').hide();
       $('oar-email').show();
    }

   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
//]]>

</script>
