<!-- RD-588 css -->
<style>
#slider_main_div{ float:left;width:730px;background: #fff url(https://www.retaildeal.biz/skin/frontend/argento/argento/images/easyslider_bg.gif) no-repeat 50% 100%;}
.likibannerright{float:left;margin:0;cursor:pointer;}
</style>
<!-- RD-588 css -->



<?php
if ($slides = $this->getSlider()->getSlides()) :
    $slider = $this->getSlider();
    $width = $slider['width'];
    $height = $slider['height'];
    $easyslide_id = $slider['easyslide_id'];
?>
    <?php if ($slider['slider_type'] == '0') : ?>
    	<div id="slider_main_div">
        <div class="easyslideslider-id" id="easyslideslider-<?php echo $easyslide_id; ?>" style='position: relative;float:left; <?php echo "width:".$width."px; height:".$height."px"; ?>'>
            <div class="scroller" style='<?php echo "width:".$width."px; height:".$height."px"; ?>'>
                <div class="content">
                    <?php $i = 0; foreach ($slides as $slide): ?>
                        <div class="section" id="section<?php echo ++$i ?>" style="width:<?php echo $width ?>px; height:<?php echo $height ?>px">
                            <a href="<?php echo $slide['target'] ?>">
                                <?php
                                    if (strncmp($slide['url'],'http', 4) == 0) {
                                        $image_src = $slide['url'];
                                    } else {
                                        $image_src = Mage::getBaseUrl('media') . 'easyslide/' . $slide['url'];
                                    }
                                ?>
                                <img src="<?php echo $image_src; ?>" width="528" height="300" alt="<?php echo $this->escapeHtml($slide['image']) ?>"/>
                            </a>
							<?php 
							//Changes by Likiext Start
							//Reason of Change: RD-137
							//if($i < 4)
							//{
							/*echo "<a style='text-decoration:none;' href=". $vPath."><div style='position:absolute; top:-5px; width:100%'>";
							if( $slide['target'] == 'catalogsearch/result/?q=grill')
							{
								echo "<div class='slide_text' style='position: absolute;z-index: 999999;top: 112px;left: 287px;font-size: 32px;color: #ffffff; font-family: condensed;margin:0 0 0 10px;'>Grills Starting at </div>";
						  echo "<div class='slide_amnt' style='position: absolute;z-index: 999999;top: 150px;left: 287px;font-size: 45px;color: #ffffff;
	font-family: boldcondensed;float:left;margin:0 0 0 10px;'><span style='float:left;'><b>$16</b></span>
	     <span class='slide_mnth' style='font-family:condensed;font-size:32px;float:left;margin:1px 0 0 5px;'>/month</span></div>";
							}
							if( $slide['target'] == 'electronics/computers/tablets.html')
							{
								echo "<div class='slide_text' style='position: absolute;z-index: 999999;top: 112px;left: 287px;font-size: 32px;color: #ffffff; font-family: condensed;margin:0 0 0 10px;'>Tablets Starting at </div>";
						  echo "<div class='slide_amnt' style='position: absolute;z-index: 999999;top: 150px;left: 287px;font-size: 45px;color: #ffffff;
	font-family: boldcondensed;float:left;margin:0 0 0 10px;'><span style='float:left;'><b>$15</b></span>
	<span class='slide_mnth' style='font-family:condensed;font-size:32px;float:left;margin:1px 0 0 5px;'>/month</span></div>";
							}
							if( $slide['target'] == 'electronics/television-video.html')
							{
								echo "<div class='slide_text' style='position: absolute;z-index: 999999;top: 112px;left: 287px;font-size: 32px;color: #ffffff; font-family: condensed;margin:0 0 0 10px;'>Televisions Starting at </div>";
						  echo "<div class='slide_amnt' style='position: absolute;z-index: 999999;top: 150px;left: 287px;font-size: 45px;color: #ffffff;
	font-family: boldcondensed;float:left;margin:0 0 0 10px;'><span style='float:left;'><b>$28</b></span>
	<span class='slide_mnth' style='font-family:condensed;font-size:32px;float:left;margin:1px 0 0 5px;'>/month</span></div>";
							}
							if( $slide['target'] == 'appliances/beverage-refrigerators.html')
							{
								echo "<div class='slide_text' style='position: absolute;z-index: 999999;top: 35px;left: 287px;font-size: 32px;color: #ffffff; font-family: condensed;margin:0 0 0 10px;'>Appliances Starting at </div>";
						  echo "<div class='slide_amnt' style='position: absolute;z-index: 999999;top: 75px;left: 320px;font-size: 45px;color: #ffffff;
	font-family: boldcondensed;float:left;margin:0 0 0 10px;'><span style='float:left;'><b>$19</b></span>
	<span class='slide_mnth' style='font-family:condensed;font-size:32px;float:left;margin:1px 0 0 5px;'>/month</span></div>";
							}
							if( $slide['target'] == 'electronics/computers/laptops.html')
							{
								echo "<div class='slide_text' style='position: absolute;z-index: 999999;top: 144px;left: 305px;font-size: 32px;color: #ffffff; font-family: condensed;margin:0 0 0 10px;'>Laptops Starting at</div>";
						  echo "<div class='slide_amnt' style='position: absolute;z-index: 999999;top: 182px;left: 305px;font-size: 45px;color: #ffffff;
	font-family: boldcondensed;float:left;margin:0 0 0 10px;'><span style='float:left;'><b>$32</b></span>
	<span class='slide_mnth' style='font-family:condensed;font-size:32px;float:left;margin:1px 0 0 5px;'>/month</span></div>";
							}
							if( $slide['target'] == 'electronics/video-game-consoles-accessories.html')
							{
								echo "<div class='slide_text' style='position: absolute;z-index: 999999;top: 53px;left: 157px;font-size: 32px;color: #ffffff; font-family: condensed;margin:0 0 0 10px;'>Video Game Starting at</div>";
						  echo "<div class='slide_amnt' style='position: absolute;z-index: 999999;top: 92px;left: 157px;font-size: 45px;color: #ffffff;
	font-family: boldcondensed;float:left;margin:0 0 0 10px;'><span style='float:left;'><b>$8</b></span>
	<span class='slide_mnth' style='font-family:condensed;font-size:32px;float:left;margin:1px 0 0 5px;'>/month</span></div>";
							}

					  echo "<div style='position: absolute;z-index: 999999;top: 230px;left: 287px;font-size: 12px;color: #ffffff;
font-family: condensed;margin:0 0 0 10px;'><span style='float:left;'></span><span style='float:left;margin:0 0 0 5px;'></span></div></div></a>";*/
					
					//Changes by Likiext End
					//} ?>
                            <?php if (!empty($slide['description'])) : ?>
                                <div class="easyslidedescription <?php echo $this->getDescriptionClassName($slide['desc_pos']); ?> <?php echo $this->getBackgroundClassName($slide['background']); ?>"><?php echo $slide['description']; ?></div>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <div class="easyslidecontrolwr">
                <div class="easyslidercontrol">
                <?php if ($this->getSlider()->getControlsType() == 'number'):
                    $slcount = count($slides);

                    for ($i = 0; $i < $slcount; $i++):
                        echo '<a href="#section'.($i+1).'" title="Slide '.($i+1).'" class="easyslidedirect">'.($i+1).'</a>';
                    endfor;
                else: ?>
                    <a href="#" class="easyslideprev" title="Previous"></a>
                    <a href="#" class="easyslidestop" title="Stop"></a>
                    <a href="#" class="easyslideplay" title="Play"></a>
                    <a href="#" class="easyslidenext" title="Next"></a>
                <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="likibannerright">
       <img id="banner_rt" src="/skin/frontend/argento/default/images/banner_right.jpg" width="196" height="300" alt="" onclick="return showForm('liki_intro_popup')" />
        </div>
		</div>
        <script type="text/javascript" charset="utf-8"> 
        var new_glider = new Glider('easyslideslider-<?php echo $easyslide_id; ?>', {
            duration     : <?php echo $slider['duration'];?>,
            autoGlide    : <?php echo (int)$slider['autoglide'];?>,
            frequency    : <?php echo $slider['frequency'];?>,
            effectType   : '<?php echo $slider['effect']; ?>'
        });
        </script>
    <?php elseif ($slider['slider_type'] == '1') : ?>
        <?php
            if (!Mage::registry('tm.load.jquery')) :
                echo $this->getLayout()->getBlock('tm.load.jquery')->toHtml();
                Mage::register('tm.load.jquery', 1);
                ?>
                <script type="text/javascript">
                    if (typeof jQuery === 'undefined') {
                        alert('jQuery library is not found. Please enable it from Easyslider configuration');
                    }
                </script>
                <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.nivo.slider.js'); ?>"></script>
                <?php
            endif;
        ?>
        <?php $theme = 'theme-' . $slider['theme'] ?>
        <div class="slider-wrapper <?php echo $theme ?>">
            <div id="slider-<?php echo $easyslide_id; ?>" class="nivoSlider">
                <?php $i = 0; foreach ($slides as $slide): ?>
                    <a href="<?php echo $slide['target'] ?>">
                        <?php
                            if (strncmp($slide['url'],'http', 4) == 0) {
                                $image_src = $slide['url'];
                            } else {
                                $image_src = Mage::getBaseUrl('media') . 'easyslide/' . $slide['url'];
                            }
                        ?>
                        <img src="<?php echo $image_src; ?>" alt="<?php echo $this->escapeHtml($slide['image']) ?>" <?php if (!empty($slide['description'])) : ?> title="#htmlcaption<?php echo $i; ?>" <?php endif; ?> />
                    </a>
                    <?php $i++; ?>
                <?php endforeach; ?>
            </div>
        </div>

        <?php $i = 0; foreach ($slides as $slide): ?>
            <?php if (!empty($slide['description'])) : ?>
                <div class="nivo-html-caption" id="htmlcaption<?php echo $i; ?>"><?php echo $slide['description'] ?></div>
            <?php endif; $i++;?>
        <?php endforeach; ?>

        <?php $nivoEffect = implode(',', $slider['nivoeffect']); ?>
        <script type="text/javascript">
            jQuery(document).ready(function(){
                jQuery('#slider-<?php echo $easyslide_id; ?>').nivoSlider({
                    'effect': '<?php echo $nivoEffect ?>',
                    'slices': <?php echo $slider['slices'] ?>, // For slice animations
                    'boxCols': <?php echo $slider['boxCols'] ?>, // For box animations
                    'boxRows': <?php echo $slider['boxRows'] ?>, // For box animations
                    'animSpeed': <?php echo $slider['animSpeed'] ?>, // Slide transition speed
                    'pauseTime': <?php echo $slider['pauseTime'] ?>, // How long each slide will show
                    'directionNav': <?php echo $slider['directionNav'] ?>, // Next & Prev navigation
                    'controlNav': <?php echo $slider['controlNav'] ?>, // 1,2,3... navigation
                    'pauseOnHover': <?php echo $slider['pauseOnHover'] ?>, // Stop animation while hovering
                    'manualAdvance': <?php echo $slider['manualAdvance'] ?>, // Force manual transitions
                    'prevText': '<?php echo Mage::helper('easyslide')->__('Prev') ?>',
                    'nextText': '<?php echo Mage::helper('easyslide')->__('Next') ?>'
                });
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
