<?php
/**
 * Redirect view file
 *
 * @category    View
 * @package     Liki Payment
 
 */
?>

<?php

// Get Liki Payment Details
$likilogin = Mage::registry( 'likilogin' );
?>

<p>Redirecting... If you have been here for a while, please <a href="javascript:document.likilogin.submit();">click here</a>.</p>
<p>Make sure you don't press the 'Back' button in your browser till your order is complete.</p>

<form name="likilogin" method="post" action="<?php echo $likilogin['liki_login_url']; ?>">
    <input type="hidden" name="EmailAddress" value="<?php echo $likilogin['email_address']; ?>">
	<input type="hidden" name="Intent" value="<?php echo $likilogin['intent']; ?>">
    <input type="hidden" name="CustomerId" value="<?php echo $likilogin['customer_id']; ?>"> 	
</form>

<script type="text/javascript">
 document.likilogin.submit();
 </script>